version: '3'

volumes:
  postgres_volume:

services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONFIG_PATH: ./local.json
      DB_HOST: postgres

  server:
    environment:
      CONFIG_PATH: ./compose.json
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
      - "8000:8000"
      - "9000:9000"
    restart: unless-stopped
    # Не придумал как ожидать завершения мигратора
    depends_on:
      postgres:
        condition: service_healthy