// Code generated by mockery v2.42.0. DO NOT EDIT.

package mockpgx

import mock "github.com/stretchr/testify/mock"

// MockCopyFromSource is an autogenerated mock type for the CopyFromSource type
type MockCopyFromSource struct {
	mock.Mock
}

type MockCopyFromSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCopyFromSource) EXPECT() *MockCopyFromSource_Expecter {
	return &MockCopyFromSource_Expecter{mock: &_m.Mock}
}

// Err provides a mock function with given fields:
func (_m *MockCopyFromSource) Err() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCopyFromSource_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockCopyFromSource_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockCopyFromSource_Expecter) Err() *MockCopyFromSource_Err_Call {
	return &MockCopyFromSource_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockCopyFromSource_Err_Call) Run(run func()) *MockCopyFromSource_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCopyFromSource_Err_Call) Return(_a0 error) *MockCopyFromSource_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCopyFromSource_Err_Call) RunAndReturn(run func() error) *MockCopyFromSource_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with given fields:
func (_m *MockCopyFromSource) Next() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCopyFromSource_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockCopyFromSource_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockCopyFromSource_Expecter) Next() *MockCopyFromSource_Next_Call {
	return &MockCopyFromSource_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockCopyFromSource_Next_Call) Run(run func()) *MockCopyFromSource_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCopyFromSource_Next_Call) Return(_a0 bool) *MockCopyFromSource_Next_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCopyFromSource_Next_Call) RunAndReturn(run func() bool) *MockCopyFromSource_Next_Call {
	_c.Call.Return(run)
	return _c
}

// Values provides a mock function with given fields:
func (_m *MockCopyFromSource) Values() ([]interface{}, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Values")
	}

	var r0 []interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCopyFromSource_Values_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Values'
type MockCopyFromSource_Values_Call struct {
	*mock.Call
}

// Values is a helper method to define mock.On call
func (_e *MockCopyFromSource_Expecter) Values() *MockCopyFromSource_Values_Call {
	return &MockCopyFromSource_Values_Call{Call: _e.mock.On("Values")}
}

func (_c *MockCopyFromSource_Values_Call) Run(run func()) *MockCopyFromSource_Values_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCopyFromSource_Values_Call) Return(_a0 []interface{}, _a1 error) *MockCopyFromSource_Values_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCopyFromSource_Values_Call) RunAndReturn(run func() ([]interface{}, error)) *MockCopyFromSource_Values_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCopyFromSource creates a new instance of MockCopyFromSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCopyFromSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCopyFromSource {
	mock := &MockCopyFromSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
