// Code generated by mockery v2.42.0. DO NOT EDIT.

package mockpgx

import (
	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockRowToFunc is an autogenerated mock type for the RowToFunc type
type MockRowToFunc[T interface{}] struct {
	mock.Mock
}

type MockRowToFunc_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockRowToFunc[T]) EXPECT() *MockRowToFunc_Expecter[T] {
	return &MockRowToFunc_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: row
func (_m *MockRowToFunc[T]) Execute(row pgx.CollectableRow) (T, error) {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(pgx.CollectableRow) (T, error)); ok {
		return rf(row)
	}
	if rf, ok := ret.Get(0).(func(pgx.CollectableRow) T); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(T)
	}

	if rf, ok := ret.Get(1).(func(pgx.CollectableRow) error); ok {
		r1 = rf(row)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRowToFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRowToFunc_Execute_Call[T interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - row pgx.CollectableRow
func (_e *MockRowToFunc_Expecter[T]) Execute(row interface{}) *MockRowToFunc_Execute_Call[T] {
	return &MockRowToFunc_Execute_Call[T]{Call: _e.mock.On("Execute", row)}
}

func (_c *MockRowToFunc_Execute_Call[T]) Run(run func(row pgx.CollectableRow)) *MockRowToFunc_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pgx.CollectableRow))
	})
	return _c
}

func (_c *MockRowToFunc_Execute_Call[T]) Return(_a0 T, _a1 error) *MockRowToFunc_Execute_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRowToFunc_Execute_Call[T]) RunAndReturn(run func(pgx.CollectableRow) (T, error)) *MockRowToFunc_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockRowToFunc creates a new instance of MockRowToFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRowToFunc[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRowToFunc[T] {
	mock := &MockRowToFunc[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
