name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "defany"
  IMAGE_NAME: "user-service"
  CONTAINER_NAME: "user-service"
  MIGRATOR_IMAGE_NAME: "user-service-migrator"
  MIGRATOR_CONTAINER_NAME: "user-service-migrator"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache-dependency-path: go.sum

      - name: Download
        run: go mod download

      - name: Build
        run: go build -o ./bin/ -v ./...

      - name: Test
        run: go test -v ./...

  linter:
    name: lint
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

          args: --timeout=30m --config=./.golangci.pipeline.yaml --issues-exit-code=0

  build-push:
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME .
          
          docker build --no-cache --push --tag $REGISTRY/$MIGRATOR_IMAGE_NAME:$TAG_NAME -f ./migrator.Dockerfile .
  deploy:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Deploy migrator to server via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME, REGISTRY, GITHUB_SHA, MIGRATOR_IMAGE_NAME, MIGRATOR_CONTAINER_NAME
          script: |
            # Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            
            # Login into docker
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} $REGISTRY
            
            # Stop running migrator
            docker stop $MIGRATOR_CONTAINER_NAME
            
            # Remove old migrator
            docker rm $MIGRATOR_CONTAINER_NAME
            
            # Run migrations service
            docker run -d --restart=always --name $MIGRATOR_IMAGE_NAME -t $REGISTRY/$MIGRATOR_IMAGE_NAME:$TAG_NAME
      - name: Deploy service to server via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME, REGISTRY, GITHUB_SHA, CONTAINER_NAME
          script: |
            # Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)

            # Login into docker
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} $REGISTRY

            # Stop running container
            docker stop $CONTAINER_NAME

            # Remove old container
            docker rm $CONTAINER_NAME

            # Run server
            docker run -d -p 50100:50001 --restart=always --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME